### ISSUE TITLE
 relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by laakie** [guncoin/guncoin#11]
/usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-neoscrypt.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libbitcoin_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [guncoin-tx] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-neoscrypt.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libbitcoin_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [guncoind] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by Bushstar** [comment]
Use the following with configure --enable-static --disable-shared

```
git clone https://github.com/guncoin/guncoin.git
cd guncoin/
cd depends/
./autogen.sh
./configure --enable-static --disable-shared --enable-asm
make clean
make
```

**Comment by laakie** [comment]
works like a charm, many thanks!
