### ISSUE TITLE
Compile error Ubuntu 16.04, 64bit

### ISSUE THREAD

**Issue by Coinomatron** [guncoin/guncoin#13]
/usr/bin/ld: crypto/.libs/libbitcoinconsensus_la-neoscrypt_asm.o: relocation R_X86_64_PC32 against symbol `blake2s_compress' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:3779: recipe for target 'libbitcoinconsensus.la' failed
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: Leaving directory '/home/wallets/guncoin/src'
Makefile:10201: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wallets/guncoin/src'
Makefile:777: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Bushstar** [comment]
```
./configure --disable-shared --enable-static
make clean
make
```

The new masternode branch does not have this problem and will soon become the default branch as it contains a hard fork set for 30 days time. Masternodes are in the final stages of testing on mainnet so there's likely to be more code changes before being considered stable.

https://github.com/guncoin/guncoin/tree/masternode

**Comment by Coinomatron** [comment]
Ah yes, that worked, thanks. Will recompile when testing is done.
