### ISSUE TITLE
RPC Error: error -8: label argument must be a valid label name or "*".

### ISSUE THREAD

**Issue by djspacedevil** [guncoin/guncoin#14]
Become an Error from RPC, with normal listtransactions

RPC Error: listtransactions -> error -8: label argument must be a valid label name or "*".

**Comment by Bushstar** [comment]
Note the following in the Bitcoin 0.17 release notes.

> listtransactions - The account named parameter has been renamed to dummy. If provided, the dummy parameter must be set to the string *, unless running with the `-deprecatedrpc=accounts` argument (in which case functionality is unchanged).
 
Source: https://bitcoin.org/en/release/v0.17.0#label-and-account-apis-for-wallet

Either use `listtransactions "*"` or `listtransactions` to return all TXs regardless of label, if you need to use the old accounts system see the info above.

**Comment by djspacedevil** [comment]
THX!

YiiMP pools require the line deprecatedrpc=accounts for normal functioning. (This may also apply to non-YiiMP pools.)
