### ISSUE TITLE
getblocktemplate - coinbasevalue incorrect

### ISSUE THREAD

**Issue by crackfoo** [guncoin/guncoin#15]
Hi, 

Using latest version, the GBT reports incorrect coinbasevalue

{
    "capabilities": [
        "proposal"
    ],
    "version": 536870912,
    "rules": [
        "csv",
        "segwit"
    ],
    "vbavailable": [],
    "vbrequired": 0,
    "previousblockhash": "d19e0e72ab11737b7a388660ee7e9ef7722be6590c719ebfd5a3f813a15b9399",
    "transactions": [],
    "coinbaseaux": {
        "flags": ""
    },
    **"coinbasevalue": 3562500000,**

It should be 7500000000 no?

**Comment by Bushstar** [comment]
3562500000 is the coinbase value for the miner. Check this coinbase transaction on CryptoID.

https://chainz.cryptoid.info/gun/tx.dws?1781395.htm

3562500000 for miner
3562500000 for masternode
375000000 for dev fund

Together they make 7500000000. Scroll down further on GBT and you'll see the following.

```
  "masternode": {
    "payee": "GrvHi5VWCpfK6uJmC5a1ZmDUP4wYddEG8G",
    "script": "76a9146acf96ae389dec73a60d45da65ff6c7c23ed3c2388ac",
    "amount": 3562500000
  },
  "masternode_payments_started": true,
  "masternode_payments_enforced": true,
  "developer": {
    "payee": "GtoEJDevx7sd4xGLXykL7wRV4JJopXYvYT",
    "script": "76a9147f6a14ad0b5a7535d16955a45df5d6c8cf22cebc88ac",
    "amount": 375000000
  }
```

**Comment by crackfoo** [comment]
every other coin in existence  puts the grand total for the block in coinbasevalue

DASH for example:

    "coinbasevalue": 310694062,
