### ISSUE TITLE
getmininginfo reports 0 hashespersec

### ISSUE THREAD

**Issue by Spiltpickle** [guncoin/guncoin#3]
I may be the only one playing with solo cpu mining with the 'built-in' miner, but after having an atom based computer running a cpu miner find a block (granted via a pool with 3rd party miner software) I figured I'd play around with solo mining with guncoin-qt.exe on windows with an i7-4790K.

When starting the miner via the 'setgenerate true 1' (or any # for the proclimit) command in the console, I get back via debug:
```
2018-02-03 08:33:03 GUNMiner started
2018-02-03 08:33:03 keypool reserve 4
2018-02-03 08:33:03 CreateNewBlock(): total size 1000
2018-02-03 08:33:03       - Connect 1 transactions: 0.00ms (0.000ms/tx, 0.000ms/txin) [0.00s]
2018-02-03 08:33:03     - Verify 0 txins: 0.00ms (0.000ms/txin) [0.00s]
2018-02-03 08:33:03 Running GUNMiner with 1 transactions in block (182 bytes)
```

CPU usage increases for the guncoin-qt.exe process, however getmininginfo reports:
```
{
"blocks" : 839954,
"currentblocksize" : 1000,
"currentblocktx" : 0,
"difficulty" : 6.86940403,
"errors" : "",
"genproclimit" : 1,
"networkhashps" : 135821225,
"pooledtx" : 0,
"testnet" : false,
"chain" : "main",
"generate" : true,
"hashespersec" : 0
}
```

hashespersec = 0. If it's not hashing, why did the cpu load increase?

Also a related issue, sending setgenerate false does not appear to do anything. CPU load remains at the higher level, and nothing is added to the debug.log file. For the CPU to come back down the guncoin-qt.exe process has to be exited and relaunched.

**Comment by Bushstar** [comment]
There's no internal mining at all in the 1.4 release which is about to be the sole viable version post hard fork on block 850,000.
