### ISSUE TITLE
relocation R_X86_64_32S against `.rodata' can not be used

### ISSUE THREAD

**Issue by djspacedevil** [guncoin/guncoin#4]
crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-neoscrypt.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

On Ubuntu 14.

**Comment by Bushstar** [comment]
Build with...

./configure --enable-static --disable-shared --enable-asm
make clean
make

**Comment by djspacedevil** [comment]
Hy,
very FAST answer, wow ;)

THX, works like a charm ;)
