### ISSUE TITLE
compilation error: Fixing libtool for -rpath problems.

### ISSUE THREAD

**Issue by goodthebest** [guncoin/guncoin#5]
I'm trying to compile binary into ubuntu 16.04, here are last few lines ending up with error. Tried many work around but to no avail. Could anyone tell me what I'm missing?
------------------------------------------

> configure: WARNING: jni headers/dependencies not found. jni support disabled
checking whether byte ordering is bigendian... no
configure: Using static precomputation: yes
configure: Using assembly optimizations: x86_64
configure: Using field implementation: 64bit
configure: Using bignum implementation: no
configure: Using scalar implementation: 64bit
configure: Using endomorphism optimizations: no
configure: Building ECDH module: no
configure: Building ECDSA pubkey recovery module: yes
configure: Using jni: no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: src/libsecp256k1-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
**Fixing libtool for -rpath problems.**

**Comment by Bushstar** [comment]
That's not a problem. What happens when you run make afterwards?

**Comment by goodthebest** [comment]
Make didn't work as it end up like that. 

However, now I'm trying  ./configure --disable-rpath;make and it seems to go smooth with Make.

**Comment by goodthebest** [comment]
Make, ressult in this error.........

> /usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-neoscrypt.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libbitcoin_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:3439: recipe for target 'guncoind' failed
make[2]: *** [guncoind] Error 1
make[2]: Leaving directory '/root/guncoin/src'
Makefile:8708: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/guncoin/src'
Makefile:689: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Bushstar** [comment]
Add this to configure...

./configure --disable-shared --enable-static --enable-asm
make clean
make
