### ISSUE TITLE
guncoin solo mining with daemon ( guncoind ) fully synced running node

### ISSUE THREAD

**Issue by goodthebest** [guncoin/guncoin#7]
I'm trying to connect my miner to guncoin daemon on the same machine but it's giving 401 error, that obviously mean unauthorized access but I've properly set guncoin.conf and connecting to right port.

when starting guncoind I'm using following 

>$guncoin>./guncoind -server -daemon -conf:guncoin.conf

**guncoin.conf**
>daemon=1
server=1
rpcuser=user
rpcpassword=password
rpcallowip=127.0.0.1
rpcallowip=1.1.1.1
rpcallowip=2.2.2.2
rpcport:42953
port:42954

Could anyone guide me how to go about solo mining using my own 'guncoind' node.

**Comment by sunk818** [comment]
do you have access to wallet? You could try running that. the `guncoin.conf` file needs to be in the same directory as your `wallet.dat` file.

If you're running `guncoind`, just try:

`guncoind --daemon` (two dashes before daemon)

You shouldn't have to put the extra parameters as it is already on the .conf file.

Try this `guncoin.conf` file:

daemon=1

> 
> server=1
> rpcuser=user
> rpcpassword=password
> rpcallowip=127.0.0.1
> rpcport=42953
> port=42954

**Comment by goodthebest** [comment]
Followed steps exactly and still the same error

>HTTP request failed: The requested URL returned error: 401
 json_rpc_call failed, retry after 30 seconds

I have setup Feathercoin successfully but this one is giving hard time?

**Comment by sunk818** [comment]
try cgminer. I believe 3.7.2 was the last (or close to) that supported GPU.

https://bitcointalk.org/index.php?topic=498671.1280

**Comment by goodthebest** [comment]
It's not device I've tried both cpu and gpu. I think it's more of daemon issue. 

It would be great if any contributor to guncoin, can come up with a solution?

**Comment by sunk818** [comment]
What version of GunCoin are you running?

try running daemon in debug mode. 

`guncoind --daemon -debug`

I divested in GunCoin, but can you run `getwork` command from the console?

**Comment by goodthebest** [comment]
Where I can see debug output?
I tried 
> getwork
but it's not part of guncoind or guncoin-cli it's returns error.

**Comment by sunk818** [comment]
If you don't have `getwork` not sure how you can solo mine. @Bushstar will know for sure. Sorry I couldn't help you.

**Comment by Bushstar** [comment]
You would mine using getblocktemplate with NSGminer which means you need to provide an address for the coinbase transaction. getwork was removed in Bitcoin 0.10 as getblocktemplate gives miners control over which transactions are included in the blocks they are creating.

Can you give us the command and options you are using to mine with?

**Comment by goodthebest** [comment]
Does that mean we can only use those miners with GBT method, in other words we can only mine with GPUs but not cpu?

**Comment by goodthebest** [comment]
this command I'm using, Feathercoin working fine with neoscrypt however with guncoin there is some issue 
> ./minerd a-  neoscrypt -o 127.0.0.1:42953 -u user -p password --coinbase-addr=GzqnPQZDf62b3EXA4DJGN3BzuxudqWkrvM

and this error I get
>Unrecognized block version: 536870912
json_rpc_call failed, retry after 30 seconds

**Comment by Bushstar** [comment]
The miner may not like Version Bit blocks. I'll check with the developer.

**Comment by Bushstar** [comment]
I've reported this to Ghostlander and should be rectified in the next NSGminer update.

**Comment by goodthebest** [comment]
I managed to connected with NSGminer the debug output I gave you was of cpuminer **mirerd** I think.

**Comment by Bushstar** [comment]
Huh, so it is. So please confirm if nsgminer does in fact appear to mine blocks?

If you could give me the block hash of any block you manage to mine that would be very useful.

**Comment by goodthebest** [comment]
Even though in verbose and debug it doesn't apparently detect any blocks often which nsgminer should every 10 mint or so. 

Yes, I managed to mine two blocks in guncoin and one in feathercoin. But they are in headless wallet in ubuntu, what is the 'curl' command I can use to retrieve block hash with json?

**Comment by Bushstar** [comment]
Use listtransactions to see the minted transactions and give me one created with a new block, I can find it from there.

**Comment by goodthebest** [comment]
I was using nsgminer as well as cpu-miner too I'not sure which exactly mined it but I suspect it's nsgminer, however you can further confirm it right?

Blockhashes are below...

a0c447000de44e2ca78ae4e71e89fa30383c123629ca963af5c11dfee496cbca

0546f734b5f55f84cb38b27f79e89185571fa90ba3b23d02be30a5aaee5d45b5
